import { Knex } from "knex";
import { ETableNames } from "../ETableNames";

export const seed = async (knex: Knex) => {
  const [{ count }] = await knex(ETableNames.cities).count<[{ count: Number }]>(
    "* as count"
  );
  if (!Number.isInteger(count) || Number(count) > 0) return;

  const citiesToInsert = citiesMinasGerais.map((nameOfCity) => ({
    name: nameOfCity,
  }));
  await knex(ETableNames.cities).insert(citiesToInsert);
};

const citiesMinasGerais = [
  "Abadia dos Dourados",
  "Abaeté",
  "Abre Campo",
  "Acaiaca",
  "Açucena",
  "Água Boa",
  "Água Comprida",
  "Aguanil",
  "Águas Formosas",
  "Águas Vermelhas",
  "Aimorés",
  "Aiuruoca",
  "Alagoa",
  "Albertina",
  "Além Paraíba",
  "Alfenas",
  "Alfredo Vasconcelos",
  "Almenara",
  "Alpercata",
  "Alpinópolis",
  "Alterosa",
  "Alto Caparaó",
  "Alto Jequitibá",
  "Alto Rio Doce",
  "Alvarenga",
  "Alvinópolis",
  "Alvorada de Minas",
  "Amparo do Serra",
  "Andradas",
  "Andrelândia",
  "Angelândia",
  "Antônio Carlos",
  "Antônio Dias",
  "Antônio Prado de Minas",
  "Araçaí",
  "Aracitaba",
  "Araçuaí",
  "Araguari",
  "Arantina",
  "Araponga",
  "Araporã",
  "Arapuá",
  "Araújos",
  "Araxá",
  "Arceburgo",
  "Arcos",
  "Areado",
  "Argirita",
  "Aricanduva",
  "Arinos",
  "Astolfo Dutra",
  "Ataléia",
  "Augusto de Lima",
  "Baependi",
  "Baldim",
  "Bambuí",
  "Bandeira",
  "Bandeira do Sul",
  "Barão de Cocais",
  "Barão de Monte Alto",
  "Barbacena",
  "Barra Longa",
  "Barroso",
  "Bela Vista de Minas",
  "Belmiro Braga",
  "Belo Horizonte",
  "Belo Oriente",
  "Belo Vale",
  "Berilo",
  "Berizal",
  "Bertópolis",
  "Betim",
  "Bias Fortes",
  "Bicas",
  "Biquinhas",
  "Boa Esperança",
  "Bocaina de Minas",
  "Bocaiúva",
  "Bom Despacho",
  "Bom Jardim de Minas",
  "Bom Jesus da Penha",
  "Bom Jesus do Amparo",
  "Bom Jesus do Galho",
  "Bom Repouso",
  "Bom Sucesso",
  "Bonfim",
  "Bonfinópolis de Minas",
  "Bonito de Minas",
  "Borda da Mata",
  "Botelhos",
  "Botumirim",
  "Brás Pires",
  "Brasilândia de Minas",
  "Brasília de Minas",
  "Brasópolis",
  "Braúnas",
  "Brumadinho",
  "Bueno Brandão",
  "Buenópolis",
  "Bugre",
  "Buritis",
  "Buritizeiro",
  "Cabeceira Grande",
  "Cabo Verde",
  "Cachoeira da Prata",
  "Cachoeira de Minas",
  "Cachoeira de Pajeú",
  "Cachoeira Dourada",
  "Caetanópolis",
  "Caeté",
  "Caiana",
  "Cajuri",
  "Caldas",
  "Camacho",
  "Camanducaia",
  "Cambuí",
  "Cambuquira",
  "Campanário",
  "Campanha",
  "Campestre",
  "Campina Verde",
  "Campo Azul",
  "Campo Belo",
  "Campo do Meio",
  "Campo Florido",
  "Campos Altos",
  "Campos Gerais",
  "Cana Verde",
  "Canaã",
  "Canápolis",
  "Candeias",
  "Cantagalo",
  "Caparaó",
  "Capela Nova",
  "Capelinha",
  "Capetinga",
  "Capim Branco",
  "Capinópolis",
  "Capitão Andrade",
  "Capitão Enéas",
  "Capitólio",
  "Caputira",
  "Caraí",
  "Caranaíba",
  "Carandaí",
  "Carangola",
  "Caratinga",
  "Carbonita",
  "Careaçu",
  "Carlos Chagas",
  "Carmésia",
  "Carmo da Cachoeira",
  "Carmo da Mata",
  "Carmo de Minas",
  "Carmo do Cajuru",
  "Carmo do Paranaíba",
  "Carmo do Rio Claro",
  "Carmópolis de Minas",
  "Carneirinho",
  "Carrancas",
  "Carvalhópolis",
  "Carvalhos",
  "Casa Grande",
  "Cascalho Rico",
  "Cássia",
  "Cataguases",
  "Catas Altas",
  "Catas Altas da Noruega",
  "Catuji",
  "Catuti",
  "Caxambu",
  "Cedro do Abaeté",
  "Central de Minas",
  "Centralina",
  "Chácara",
  "Chalé",
  "Chapada do Norte",
  "Chapada Gaúcha",
  "Chiador",
  "Cipotânea",
  "Claraval",
  "Claro dos Poções",
  "Cláudio",
  "Coimbra",
  "Coluna",
  "Comendador Gomes",
  "Comercinho",
  "Conceição da Aparecida",
  "Conceição da Barra de Minas",
  "Conceição das Alagoas",
  "Conceição das Pedras",
  "Conceição de Ipanema",
  "Conceição do Mato Dentro",
  "Conceição do Pará",
  "Conceição do Rio Verde",
  "Conceição dos Ouros",
  "Cônego Marinho",
  "Confins",
  "Congonhal",
  "Congonhas",
  "Congonhas do Norte",
  "Conquista",
  "Conselheiro Lafaiete",
  "Conselheiro Pena",
  "Consolação",
  "Contagem",
  "Coqueiral",
  "Coração de Jesus",
  "Cordisburgo",
  "Cordislândia",
  "Corinto",
  "Coroaci",
  "Coromandel",
  "Lagoa da Prata",
  "Lagoa dos Patos",
  "Lagoa Dourada",
  "Lagoa Formosa",
  "Lagoa Grande",
  "Lagoa Santa",
  "Lajinha",
  "Lambari",
  "Lamim",
  "Laranjal",
  "Lassance",
  "Lavras",
  "Leandro Ferreira",
  "Leme do Prado",
  "Leopoldina",
  "Liberdade",
  "Lima Duarte",
  "Limeira do Oeste",
  "Lontra",
  "Luisburgo",
  "Luislândia",
  "Luminárias",
  "Luz",
  "Machacalis",
  "Machado",
  "Madre de Deus de Minas",
  "Malacacheta",
  "Mamonas",
  "Manga",
  "Manhuaçu",
  "Manhumirim",
  "Mantena",
  "Mar de Espanha",
  "Maravilhas",
  "Maria da Fé",
  "Mariana",
  "Marilac",
  "Mário Campos",
  "Maripá de Minas",
  "Marliéria",
  "Marmelópolis",
  "Martinho Campos",
  "Martins Soares",
  "Mata Verde",
  "Materlândia",
  "Mateus Leme",
  "Mathias Lobato",
  "Matias Barbosa",
  "Matias Cardoso",
  "Matipó",
  "Mato Verde",
  "Matozinhos",
  "Matutina",
  "Medeiros",
  "Medina",
  "Mendes Pimentel",
  "Mercês",
  "Mesquita",
  "Minas Novas",
  "Minduri",
  "Mirabela",
  "Miradouro",
  "Miraí",
  "Miravânia",
  "Moeda",
  "Moema",
  "Monjolos",
  "Monsenhor Paulo",
  "Montalvânia",
  "Monte Alegre de Minas",
  "Monte Azul",
  "Monte Belo",
  "Monte Carmelo",
  "Monte Formoso",
  "Monte Santo de Minas",
  "Monte Sião",
  "Montes Claros",
  "Montezuma",
  "Morada Nova de Minas",
  "Morro da Garça",
  "Morro do Pilar",
  "Munhoz",
  "Muriaé",
  "Mutum",
  "Muzambinho",
  "Nacip Raydan",
  "Nanuque",
  "Naque",
  "Natalândia",
  "Natércia",
  "Nazareno",
  "Nepomuceno",
  "Ninheira",
  "Nova Belém",
  "Nova Era",
  "Nova Lima",
  "Nova Módica",
  "Nova Ponte",
  "Nova Porteirinha",
  "Nova Resende",
  "Nova Serrana",
  "Nova União",
  "Novo Cruzeiro",
  "Novo Oriente de Minas",
  "Novorizonte",
  "Olaria",
  "Olhos-d'Água",
  "Olímpio Noronha",
];
